### ISSUE TITLE
Problem signing a file more than once

### ISSUE THREAD

**Issue by mcalcano** [vizicsaba89/pdf-signer#10]
Hi guys, i'm having a problem when signing a file more than once.
What happens is that only the last signature (always the last one) stays valid but the ones before change to invalid.

![image](https://user-images.githubusercontent.com/17711421/84294569-5b257380-ab17-11ea-82c2-9a5c02164674.png)

If I sign it again, I get the same error, last signature added is valid but the rest are invalid due to the same error "There are errors in the formatting or information contained in this signature (The signature byte range is invalid)"

Has anyone solved this issue?
It happens with any file, I've tried with more than 50 different files.

Thanks in advance!

**Comment by pankucsi** [comment]
Helo @mcalcano 

First of all, srry for the late reply. Can you send us one of these files ? At the moment we are just testing manually, but this aproach is passing. We are able to sign twice the same pdf without invalidat the first signature.

**Comment by pankucsi** [comment]
Due the inactivite I close the issue.
