### ISSUE TITLE
can't signed Any PDf Created By PDFlib library 

### ISSUE THREAD

**Issue by biloo-dev** [vizicsaba89/pdf-signer#19]
I have adding an image on each page of pdf file by the pdf-lib library https://github.com/Hopding/pdf-lib
But I cannot sign the file after modifying it  
 
![eeee](https://user-images.githubusercontent.com/37638323/97112397-563b1800-16e4-11eb-8895-734a3df3a246.png)

i have try to sign any pdf created by this library but still same issue 

Is there a solution to this problem
Or any other way to insert an image to a pre-existing PDF file

**Comment by pankucsi** [comment]
Can you attach the modified PDF file ? 

You could insert an image as a widget sign, but you can't insert a standalone image.

**Comment by biloo-dev** [comment]
PDF 1 - simple.pdf
[simple.pdf](https://github.com/vizicsaba89/pdf-signer/files/5435440/simple.pdf)

i got this Error from pdf 1===> 
![fdfdfd](https://user-images.githubusercontent.com/37638323/97113783-d9606c00-16ec-11eb-8747-1e01d991178f.png)

PDF 2 - embed_png_and_jpeg_images.pdf
[embed_png_and_jpeg_images.pdf](https://github.com/vizicsaba89/pdf-signer/files/5435443/embed_png_and_jpeg_images.pdf)

i got this Error  from pdf 2 ===> 
![eeee](https://user-images.githubusercontent.com/37638323/97113791-e41b0100-16ec-11eb-9ca3-82cdca567e55.png)

**Comment by biloo-dev** [comment]
i have fixed my problem with for use other lib   **hummus-recipe** for edit my pdf file 
https://github.com/chunyenHuang/hummusRecipe#readme
