### ISSUE TITLE
Invalid filter algorithm

### ISSUE THREAD

**Issue by biloo-dev** [vizicsaba89/pdf-signer#20]
When I tried my png image, I ran into this error
![fdfdfffff](https://user-images.githubusercontent.com/37638323/97189736-34559a00-17a5-11eb-9055-dd87b0d743af.png)

this is my png
![img](https://user-images.githubusercontent.com/37638323/97189875-5d762a80-17a5-11eb-8cc7-7354946b8449.png)

**Comment by vizicsaba89** [comment]
Hi @biloo-dev!

Thank you for opening this issue, the problem lies in the png-js lib version we're currently using.
It does not supports interlaced png images.
I've just updated our dependency to a newer version and it seems that fixed your problem, we will publish a new version soon!

**Comment by vizicsaba89** [comment]
Published a fixed version, closing.
