### ISSUE TITLE
Add placeholder for signature in one step and then sign the document on a later run 

### ISSUE THREAD

**Issue by vicpara** [vizicsaba89/pdf-signer#23]
Hi,
I'm trying to add a signature AcroField '/Sig' for signature in PDF files after I generate them using `pdf-signer`. 
Is there a way to do this?

**Comment by pankucsi** [comment]
Yes, please check out the [sign.spec.ts](https://github.com/vizicsaba89/pdf-signer/blob/22cec8db04fcff44b26f602edc01f6ed6efea569/src/sign.spec.ts#L74) file.

```javascript
  it('sign once -> save -> sign again', ...
```
