### ISSUE TITLE
Depends on vulnerable versions of node-forge

### ISSUE THREAD

**Issue by alonyman** [vizicsaba89/pdf-signer#25]
on node i am getting warnings about 2 high severity vulnerabilities because of Depends on vulnerable versions of node-forge
node-forge  <=0.9.2

I will be glad ifd you can update the pdf-signer the newest node-forge .
since i new to node i cant do it myself
thanks

**Comment by pankucsi** [comment]
I updated the dependencies version, 

node-forge's version has been went up to 0.10.0 from 0.9.2
