### ISSUE TITLE
Sign a PDF with existing /Sig field

### ISSUE THREAD

**Issue by vicpara** [vizicsaba89/pdf-signer#26]
Hi,
Is there a way to sign PDF files with existing AcroFields of type /Sig ? 
I would appreciate any guidance in how to do it using your library. I like all the extra features you added on top of `node-signpdf`.
Thanks

**Comment by pankucsi** [comment]
Helo @vicpara 

Please take a look on the *.spec.ts files for use cases. You will find the most usable solutions for this lib.

Unfortunately we are lacking on documentations and freetime for this project but pls stay tuned!
