### ISSUE TITLE
When I change the image to transparent png, the background color of the image will become black after signing

### ISSUE THREAD

**Issue by ccmBlockChain** [vizicsaba89/pdf-signer#3]
When I change the image to transparent png, the background color of the image will become black after signing

` imagePath: './assets/icon_next@3x.png'`

The results are as follows:
![image](https://user-images.githubusercontent.com/59789702/74812922-4e45ff80-532f-11ea-9e71-edde2081868e.png)

**Comment by pankucsi** [comment]
Thank you for opening this issue, we will try fix and look after these issue as soon as we can.

**Comment by pankucsi** [comment]
Thank you for opening this issue, we will look after and try to fix these issue as soon as we can.

**Comment by HanderUp** [comment]
@pankucsi @vizicsaba89 
Hello, I also encountered this problem. After trying, I did this. I don’t know if it’s correct. I hope you can point it out, thinks!

>png-appender.ts : 50
```javascript
pngBaseData['SMask'] = [val, val]
```

>png-appender.ts : 58
```javascript
pngBaseData['SMask'] = mask
```

>png-appender.ts : 67
```javascript
pngBaseData['SMask'] = sMask
pngBaseData['Length'] = imgData.length
```

>png-appender.ts : 128
```javascript
const getSmask = (pdf: PdfCreator, image: any, alphaChannel: Buffer) => {
  let sMask
  if (image.hasAlphaChannel) {
    const sMaskData: PNGBaseData = {
      Type: 'XObject',
      Subtype: 'Image',
      BitsPerComponent: 8,
      Width: image.width,
      Height: image.height,
      Length: alphaChannel.length,
      Filter: 'FlateDecode',
      ColorSpace: 'DeviceGray',
    }

    sMask = pdf.appendStream(sMaskData, alphaChannel)
  }

  return sMask
}
```

The results are as follows:
Before:
![image](https://user-images.githubusercontent.com/22523322/103746462-1bd2ed00-503c-11eb-991b-be3c25d4b3cc.png)

After:
![image](https://user-images.githubusercontent.com/22523322/103746573-42912380-503c-11eb-80a9-2bf92ff6074f.png)

**Comment by pankucsi** [comment]
@HanderUp 

Nice one ! I will publish this fix in the next version.
