### ISSUE TITLE
Change the 'signature box' size

### ISSUE THREAD

**Issue by willmartinsmg** [vizicsaba89/pdf-signer#38]
I need to change the size of the 'signature box' which is printed in the pdf. It is possible?

![box-pdf-signer](https://user-images.githubusercontent.com/4895004/130346946-7222f994-3d55-4d23-9472-ae3ed4b79b31.png)

**Comment by willmartinsmg** [comment]
Sorry to inconvenience you, but can you just let me know if you can change the size of the "signature box"?

**Comment by pankucsi** [comment]
With the signatureCoordinates property, you can change the annotation appearance. You can find an example in the tests files, but let me show you one example:

```
{
      ...
    annotationAppearanceOptions: {
      signatureCoordinates: { left: 0, bottom: 0, right: 200, top: 200 },
      signatureDetails: [...],
    },
  }
```



![kép](https://user-images.githubusercontent.com/18686813/131357482-1db8521c-6dc2-4472-bc50-e5f4159a6d24.png)
