### ISSUE TITLE
How to add annotationAppearance in last page of multipages pdf ?

### ISSUE THREAD

**Issue by nguyenbinhdai** [vizicsaba89/pdf-signer#5]
I try signing multipages PDF  but AnnotationApparance in first page. How do dipslay it in last page ?
Thanks you !

**Comment by vizicsaba89** [comment]
Thank you for opening the issue.
Unfortunately, currently it's only possible to display the signature on the first page.
We've been working on this issue, i think it'll be resolved this week!

**Comment by vizicsaba89** [comment]
@nguyenbinhdai The issue has been fixed, merged to master and publish to npm in version 1.0.1.

Closing.

**Comment by nguyenbinhdai** [comment]
Thanks vizicsaba89 !
