### ISSUE TITLE
不能签名

### ISSUE THREAD

**Issue by iozhaq** [vizicsaba89/pdf-signer#9]
你好，当我的pdf中的交叉引用格式是流，而不是交叉表的时候，获取xref会失败，不知道可否帮我解决下，当然我也可以协助解决。

**Comment by pankucsi** [comment]
Helo Iozhaq,

In advance sorry if I miss understand your issue, but i used google translator. 
Pdf-signer cant handle pdf stream in the moment. It only can works with pdf which built on XREF tables.

**Comment by pankucsi** [comment]
Due the inactivite I had closed the issue.
